# GitHub Pages Configuration
title: "Clinical Skill-Mix Dimensions"
description: "Interactive visualization of Clinical Skill-Mix dimensions for healthcare AI evaluation"
url: "https://your-username.github.io"
baseurl: "/Clinical-World-Model"

# Publish from website folder
source: website

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - README.md